apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Jaeger
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger-uid
          urlDisplayLabel: "View in Jaeger"

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    version: 1
    editable: false
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger-uid
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "Open in Jaeger"

  - name: Jaeger
    type: jaeger
    uid: jaeger-uid
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    version: 1
    editable: false
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus-uid
        spanStartTimeShift: "-2m"
        spanEndTimeShift: "2m"
        filterByTraceID: false
        filterBySpanID: false
